<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container61wSCTd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container61wSCTd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container61wSCTd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container61wSCTd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container61wSCTd\srcDevDebugProjectContainer(array(
    'container.build_hash' => '61wSCTd',
    'container.build_id' => 'e5581d9b',
    'container.build_time' => 1524494172,
), __DIR__.\DIRECTORY_SEPARATOR.'Container61wSCTd');
