<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.auto_command.make_form' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/MakerInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/Maker/AbstractMaker.php';
include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/Maker/MakeForm.php';
include_once $this->targetDirs[4].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/Command/MakerCommand.php';

$this->privates['maker.auto_command.make_form'] = $instance = new \Symfony\Bundle\MakerBundle\Command\MakerCommand(new \Symfony\Bundle\MakerBundle\Maker\MakeForm(($this->privates['maker.doctrine_entity_helper'] ?? $this->load('getMaker_DoctrineEntityHelperService.php'))), ($this->privates['maker.file_manager'] ?? $this->load('getMaker_FileManagerService.php')));

$instance->setName('make:form');

return $instance;
