<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.auto_command.make_entity' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/MakerInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/Maker/AbstractMaker.php';
include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/Maker/MakeEntity.php';
include_once $this->targetDirs[4].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[4].'/vendor/symfony/maker-bundle/src/Command/MakerCommand.php';

$a = ($this->privates['maker.file_manager'] ?? $this->load('getMaker_FileManagerService.php'));

$this->privates['maker.auto_command.make_entity'] = $instance = new \Symfony\Bundle\MakerBundle\Command\MakerCommand(new \Symfony\Bundle\MakerBundle\Maker\MakeEntity($a, $this->targetDirs[4], ($this->services['doctrine'] ?? $this->getDoctrineService())), $a);

$instance->setName('make:entity');

return $instance;
