<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Components\FrontOffice\Controller\AuthController' shared autowired service.

include_once $this->targetDirs[4].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[4].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[4].'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once $this->targetDirs[4].'/src/Components/FrontOffice/Controller/AuthController.php';

return $this->services['App\Components\FrontOffice\Controller\AuthController'] = new \App\Components\FrontOffice\Controller\AuthController();
