<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cache.validator' shared service.

include_once $this->targetDirs[4].'/vendor/psr/cache/src/CacheItemPoolInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/cache/Adapter/AdapterInterface.php';
include_once $this->targetDirs[4].'/vendor/psr/log/Psr/Log/LoggerAwareInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/cache/ResettableInterface.php';
include_once $this->targetDirs[4].'/vendor/psr/log/Psr/Log/LoggerAwareTrait.php';
include_once $this->targetDirs[4].'/vendor/symfony/cache/Traits/AbstractTrait.php';
include_once $this->targetDirs[4].'/vendor/symfony/cache/Adapter/AbstractAdapter.php';

return $this->privates['cache.validator'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('ZqZoTV-U9k', 0, $this->getParameter('container.build_id'), ($this->targetDirs[0].'/pools'), ($this->privates['logger'] ?? $this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()));
